import { ChiefGuest, AgendaItem } from './types';

export const EVENT_DATE = '2026-08-20T09:00:00+05:30'; // Target date in the third week of August 2026

export const CHIEF_GUESTS: ChiefGuest[] = [
  {
    id: 'guest-1',
    name: "Hon'ble Thiru R. Kumar",
    designation: 'Minister for Artificial Intelligence, IT, and Digital Services',
    organization: 'Government of Tamil Nadu',
    bio: 'Pioneering tech policies, AI ethical guidelines, and digital governance models to accelerate responsible AI adoption and digital growth.',
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-2',
    name: 'Padma Shri Prof. V. Kamakoti',
    designation: 'Director',
    organization: 'IIT Madras',
    bio: 'Distinguished computer scientist leading indigenous microprocessor initiatives (SHAKTI) and fostering deep-tech academic research.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-3',
    name: 'Mr. Vedagiri Venkatraman',
    designation: 'Former Vice President',
    organization: 'Bank of New York Mellon Corporation',
    bio: 'Architecting secure fintech architectures, global transactional banking hubs, and advising modern AI compliance systems.',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-4',
    name: 'Mr. Sakthivel',
    designation: 'Founder',
    organization: 'AE Soft Pvt. Ltd.',
    bio: 'Pioneering local enterprise software solutions, database engineering frameworks, and fostering software developers across Tamil Nadu.',
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-5',
    name: 'Mr. Sridhar Vembu',
    designation: 'Co-Founder',
    organization: 'Zoho Corporation',
    bio: 'Championing product-led SaaS innovation from India while creating tech development centers in rural and semi-urban communities.',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-6',
    name: 'Mr. Dharaneetharan G. D.',
    designation: 'Founder',
    organization: 'Social Eagle',
    bio: 'Digital marketing authority and mentor helping organizations implement scalable AI systems for corporate growth and audience engagement.',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-7',
    name: 'Mr. S. Mohammed Sharif',
    designation: 'GST & Income Tax Practitioner',
    organization: 'Sharif Associates',
    bio: 'Expert in finance legislation, audit automation systems, and leveraging intelligent algorithms in regulatory compliance reporting.',
    imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-8',
    name: 'Dr. Shenyhil',
    designation: 'Cosmetologist',
    organization: 'Aesthetic Care Clinics',
    bio: 'Combining dermatology with advanced medical imaging models and AI-driven diagnostic frameworks for customized care solutions.',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&h=400&fit=crop',
  }
];

export const AGENDA_ITEMS: AgendaItem[] = [
  // DAY 1
  {
    id: 'day1-1',
    time: '09:00 - 09:30',
    title: 'Registration & Welcome Coffee',
    speaker: null,
    track: 'Interactive',
    day: 1,
  },
  {
    id: 'day1-2',
    time: '09:30 - 10:15',
    title: 'Inaugural Keynote: AI Policies and Nation-Building',
    speaker: "Hon'ble Thiru R. Kumar (Minister for AI, IT & Digital Services)",
    track: 'Keynote',
    day: 1,
  },
  {
    id: 'day1-3',
    time: '10:15 - 11:30',
    title: 'Fireside: Developing Indigenous Microprocessors and Edge Computing',
    speaker: 'Padma Shri Prof. V. Kamakoti (Director, IIT Madras)',
    track: 'Tech Innovation',
    day: 1,
  },
  {
    id: 'day1-4',
    time: '11:30 - 12:30',
    title: 'SaaS Scaling & Rural Technology Hubs',
    speaker: 'Mr. Sridhar Vembu (Zoho Corporation)',
    track: 'Skill Building',
    day: 1,
  },
  {
    id: 'day1-5',
    time: '12:30 - 13:30',
    title: 'Networking Lunch & AI Project Expo',
    speaker: null,
    track: 'Interactive',
    day: 1,
  },
  {
    id: 'day1-6',
    time: '13:30 - 15:00',
    title: 'Panel Discussion: Deploying AI Systems in Global Fintech Systems',
    speaker: 'Mr. Vedagiri Venkatraman, Mr. Sakthivel, Mr. Dharaneetharan G. D.',
    track: 'Keynote',
    day: 1,
  },
  {
    id: 'day1-7',
    time: '15:00 - 16:30',
    title: 'AI in Aesthetics and Medical Imaging Diagnostics',
    speaker: 'Dr. Shenyhil (Cosmetologist)',
    track: 'Tech Innovation',
    day: 1,
  },
  {
    id: 'day1-8',
    time: '16:30 - 17:30',
    title: 'Taxation and Audit Systems Automation',
    speaker: 'Mr. S. Mohammed Sharif (GST & Income Tax Practitioner)',
    track: 'Skill Building',
    day: 1,
  },
  // DAY 2
  {
    id: 'day2-1',
    time: '09:00 - 09:30',
    title: 'Day 2 Recap & Warmup',
    speaker: 'unAi Tech Mentors',
    track: 'Interactive',
    day: 2,
  },
  {
    id: 'day2-2',
    time: '09:30 - 11:00',
    title: 'Masterclass: Building Enterprise Applications on Low-Compute Systems',
    speaker: 'Mr. Sakthivel (Founder, AE Soft)',
    track: 'Skill Building',
    day: 2,
  },
  {
    id: 'day2-3',
    time: '11:00 - 12:30',
    title: 'Scaling Tech and Content Ecosystems with Generative AI',
    speaker: 'Mr. Dharaneetharan G. D. (Founder, Social Eagle)',
    track: 'Tech Innovation',
    day: 2,
  },
  {
    id: 'day2-4',
    time: '12:30 - 13:30',
    title: 'Lunch & Student-Mentor Speed Mentoring',
    speaker: null,
    track: 'Interactive',
    day: 2,
  },
  {
    id: 'day2-5',
    time: '13:30 - 15:30',
    title: 'Fintech Platforms Security, Blockchain, & AI Middleware',
    speaker: 'Mr. Vedagiri Venkatraman (Former VP, BNY Mellon)',
    track: 'Tech Innovation',
    day: 2,
  },
  {
    id: 'day2-6',
    time: '15:30 - 16:30',
    title: 'AI Policies, IP Laws, and Compliance for Innovators',
    speaker: 'Government Policy Advisors & Thiru R. Kumar',
    track: 'Keynote',
    day: 2,
  },
  {
    id: 'day2-7',
    time: '16:30 - 17:30',
    title: 'Closing Ceremony & E-Certificate Distribution Guide',
    speaker: 'unAi Tech Leadership',
    track: 'Interactive',
    day: 2,
  }
];
