import { ChiefGuest, AgendaItem } from './types';

export const EVENT_DATE = '2026-02-15T09:00:00+05:30'; // TARGET DATE: Feb 15, 2026

export const CHIEF_GUESTS: ChiefGuest[] = [
  {
    id: 'guest-1',
    name: 'Dr. Arisaran K.',
    designation: 'Director of Autonomous Systems',
    organization: 'UNAI Tech',
    bio: 'Pioneering work in low-compute reinforcement learning agents. Leads edtech engineering initiatives across India.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-2',
    name: 'Priyanka Sen',
    designation: 'Lead AI Engineer',
    organization: 'NeuralCore Chennai',
    bio: 'Specialist in custom LLM finetuning and small language models for edge devices. Former researcher at IIT Madras.',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-3',
    name: 'Rajesh Subramanian',
    designation: 'Founder & Architect',
    organization: 'Cognitive Labs',
    bio: 'Architecting distributed agent systems for industrial automation. Deep believer in hands-on student building.',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-4',
    name: 'Dr. Meera Alagappan',
    designation: 'Head of Data Science',
    organization: 'Sankara AI Hospital Group',
    bio: 'Deploying computer vision systems in clinical settings to detect early retinopathy and ophthalmic conditions.',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-5',
    name: 'Vikram Karthik',
    designation: 'Chief Robotics Architect',
    organization: 'Bots & Beyond India',
    bio: 'Building ROS-based autonomous delivery fleets for Chennai\'s dense urban settings. Advisor to student clubs.',
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&h=400&fit=crop',
  },
  {
    id: 'guest-6',
    name: 'Asha Sundar',
    designation: 'AI Product Strategy Director',
    organization: 'UNAI EdTech Foundation',
    bio: 'Focused on scaling practical AI literacy to over 50,000 engineering students in tier-2 and tier-3 colleges.',
    imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=400&h=400&fit=crop',
  }
];

export const AGENDA_ITEMS: AgendaItem[] = [
  // DAY 1
  {
    id: 'day1-1',
    time: '09:00 - 09:30',
    title: 'Registration & Welcome Coffee',
    speaker: null,
    track: 'Interactive',
    day: 1,
  },
  {
    id: 'day1-2',
    time: '09:30 - 10:15',
    title: 'Keynote: Architecting Autonomous Systems in India',
    speaker: 'Dr. Arisaran K. (UNAI Tech)',
    track: 'Keynote',
    day: 1,
  },
  {
    id: 'day1-3',
    time: '10:15 - 11:30',
    title: 'Hands-on: Building Your First Agent with Local Models',
    speaker: 'Priyanka Sen (NeuralCore)',
    track: 'Skill Building',
    day: 1,
  },
  {
    id: 'day1-4',
    time: '11:30 - 12:30',
    title: 'The Shift to Edge AI: SLMs over APIs',
    speaker: 'Rajesh Subramanian (Cognitive Labs)',
    track: 'Tech Innovation',
    day: 1,
  },
  {
    id: 'day1-5',
    time: '12:30 - 13:30',
    title: 'Networking Lunch & AI Project Exhibition',
    speaker: null,
    track: 'Interactive',
    day: 1,
  },
  {
    id: 'day1-6',
    time: '13:30 - 15:00',
    title: 'Panel Discussion: What Chennai Employers Look for in AI Freshers',
    speaker: 'Asha Sundar, Dr. Meera Alagappan, Vikram Karthik',
    track: 'Keynote',
    day: 1,
  },
  {
    id: 'day1-7',
    time: '15:00 - 16:30',
    title: 'Deep Dive: Computer Vision and Medical Diagnostics',
    speaker: 'Dr. Meera Alagappan (Sankara AI)',
    track: 'Tech Innovation',
    day: 1,
  },
  {
    id: 'day1-8',
    time: '16:30 - 17:30',
    title: 'Lightning Talks: Student Builders Showcase',
    speaker: 'Selected Student Projects',
    track: 'Skill Building',
    day: 1,
  },
  // DAY 2
  {
    id: 'day2-1',
    time: '09:00 - 09:30',
    title: 'Day 2 Recap & Warmup',
    speaker: 'UNAI EdTech Mentors',
    track: 'Interactive',
    day: 2,
  },
  {
    id: 'day2-2',
    time: '09:30 - 11:00',
    title: 'Masterclass: Deploying Production RAG at Scale',
    speaker: 'UNAI Engineering Team',
    track: 'Skill Building',
    day: 2,
  },
  {
    id: 'day2-3',
    time: '11:00 - 12:30',
    title: 'Robotics & AI: Bridging Simulation and Reality in ROS',
    speaker: 'Vikram Karthik (Bots & Beyond)',
    track: 'Tech Innovation',
    day: 2,
  },
  {
    id: 'day2-4',
    time: '12:30 - 13:30',
    title: 'Lunch & Student-Mentor Speed Dating',
    speaker: null,
    track: 'Interactive',
    day: 2,
  },
  {
    id: 'day2-5',
    time: '13:30 - 15:30',
    title: 'Hack-in-a-Box: Building AI Assistants with WebGPU',
    speaker: 'Priyanka Sen & Team',
    track: 'Skill Building',
    day: 2,
  },
  {
    id: 'day2-6',
    time: '15:30 - 16:30',
    title: 'The Future of AI Literacy in Indian Universities',
    speaker: 'Asha Sundar (UNAI EdTech)',
    track: 'Keynote',
    day: 2,
  },
  {
    id: 'day2-7',
    time: '16:30 - 17:30',
    title: 'Closing Ceremony & E-Certificate Distribution Guide',
    speaker: 'Dr. Arisaran K.',
    track: 'Interactive',
    day: 2,
  }
];
